#!/usr/bin/env python3


import fsqc

from fsqc.fsqcMain import _parse_arguments

if __name__ == "__main__":

    # say hello
    print("")
    print("-----------------------------")
    print("fsqc")
    print("-----------------------------")
    print("")

    # parse arguments
    argsDict = _parse_arguments()

    # run fsqc
    if argsDict is not None:
        fsqc.run_fsqc(subjects_dir=None, output_dir=None, argsDict=argsDict)
