---
title: "Interaction statistics"
author: "Tobias Wolff"
date: "7/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = TRUE}
# load data
d<-read.csv("/home/wolfft/qatools/adni-results/quality_checker_v2.csv")
e<-read.csv("/home/wolfft/qatools/adni-results/adni-qc-table1.csv")
d<-merge(d,e,by.x="Subject",by.y="Image.ID")

#Preprocess data
d<-droplevels(d)
d$tmp<-ave(d$Subject,d$Subject.ID,FUN=function(x){x[1]})
dSingle<-subset(d,subset=is.element(d$Subject,unique(d$tmp)))
dSingle<-droplevels(dSingle)

# dSingle contains only one image per subject. Aim is to look for the interaction statistics. This time we will concentrate on the holes
dSingle$AgeGroup<-as.factor(round(dSingle$Age/5)*5)
dSingle$AgeDemeaned<-dSingle$Age-mean(dSingle$Age)  
dSingle$Holes_LHGroup<-as.factor(round(dSingle$Holes_LH/20)*20)
dSingle$Holes_RHGroup<-as.factor(round(dSingle$Holes_RH/20)*20)

# Dismiss the unknown Sex from the dataset
dSingle<-subset(dSingle,subset=Sex!="X")

# dSingle contains only one image per subject. Aim is to look for the interaction statistics. This time we will concentrate on the holes
```

## Descriptive statistics 

### Number of holes 
```{r, echo=FALSE}
par(mfrow=c(1,2))

boxplot(dSingle$Holes_LH~dSingle$AgeGroup, ylab = "Number of holes", xlab = "Age-group", main = "LH Holes over Age-group")
boxplot(dSingle$Holes_RH~dSingle$AgeGroup, ylab = "Number of holes", xlab = "Age-group", main = "RH Holes over Age-group")

boxplot(dSingle$Age~dSingle$Holes_LHGroup, ylab = "Age", xlab = "Number of holes", main = " Age over LH holes-group")
boxplot(dSingle$Age~dSingle$Holes_RHGroup, ylab = "Age", xlab = "Number of holes", main = " Age over RH holes-group") 

boxplot(dSingle$Holes_LH~dSingle$Sex, ylab = "Number of holes", xlab = "Sex", main = "LH Holes over sex")
boxplot(dSingle$Holes_RH~dSingle$Sex, ylab = "Number of holes", xlab = "Sex", main = "RH Holes over sex")

boxplot(dSingle$Holes_LH~dSingle$Research.Group, ylab = "Number of holes", xlab = "Research Group", las = 2, main = "LH Holes over Research Group")
boxplot(dSingle$Holes_RH~dSingle$Research.Group, ylab = "Number of holes", xlab = "Research Group", las = 2, main = "RH Holes over Research Group")
```

## Models

### Linear Model 


```{r, echo=FALSE}
# Original parameters LH Holes 
plot(dSingle$Holes_LH~dSingle$Age, main = "The single dataset holes over age")
model<-lm(dSingle$Holes_LH~dSingle$Age)
abline(model,col="red")
```
```{r, echo=FALSE}
# Centered age LH Holes
plot(dSingle$Holes_LH~dSingle$AgeDemeaned, main = " The single dataset holes over the averaged age")
model_mean<-lm(dSingle$Holes_LH~dSingle$AgeDemeaned)
abline(model_mean,col="red")

```

```{r, echo=FALSE}
# Look at the residues of the original model 
plot(model$residuals, main ="Residuals of the original model")
# The residuals of the centered model: 
plot(dSingle$AgeDemeaned,model$residuals, main = "Residuals of the averaged model")
# Problems: Decreasing tendancy and not scattered equally
```

## Evaluation 

### Simple Statistics
```{r, echo=TRUE}
# Significant link between LH Holes and Age?
model<-lm(dSingle$Holes_LH~dSingle$Age)
summary(model)

model_mean<-lm(dSingle$Holes_LH~dSingle$AgeDemeaned)
summary(model_mean)
# Yes significant link between LH Holes and Age p < 0.05 
```

```{r, echo=TRUE}
# Significant link between RH Holes and Age?
model<-lm(dSingle$Holes_RH~dSingle$Age)
summary(model)

model_mean<-lm(dSingle$Holes_RH~dSingle$AgeDemeaned)
summary(model_mean)
# Yes significant link between RH Holes and Age p < 0.05 
```

```{r, echo=TRUE}
# Significant link between LH Holes and Sex?
model<-lm(dSingle$Holes_LH~dSingle$Sex)
summary(model)
# Yes significant link between LH Holes and Sex p < 0.05 

```

### Complex Statistics

```{r, echo=TRUE}
# Link between holes and the Interaction of sex and age?
summary(lm(dSingle$Holes_LH~dSingle$Sex+dSingle$AgeDemeaned))
summary(lm(dSingle$Holes_LH~dSingle$Sex+dSingle$Age))
# No difference if meaned or original age is taken except for the intercept, whereas the mean age intercept does make more sense. Therefore the following statistics are computed for the meaned age. 
# Conclusion: Significant influence of the age and of the sex, whereas, the age influences more than the sex. 
```

```{r, echo=TRUE}
# Link between holes and the Interaction of sex and age?
summary(lm(dSingle$Holes_LH~dSingle$Sex+dSingle$AgeDemeaned))
summary(lm(dSingle$Holes_LH~dSingle$Sex+dSingle$Age))
# No difference if meaned or original age is taken except for the intercept, whereas the mean age intercept does make more sense. Therefore the following statistics are computed for the meaned age. 
# Conclusion: Significant influence of the age and of the sex, whereas, the age influences more than the sex. 
# The multiple R-squared value is rather low, indicating that the model is rather bad.
```

```{r, echo=TRUE}
# Link between holes and the Interaction of sex and age?
summary(lm(dSingle$Holes_LH~dSingle$Sex*dSingle$AgeDemeaned))
# The interaction between the parameters Age and sex does not influence the outcome of the data. 
```
```{r, echo=TRUE}
# Link between holes and the Interaction of ResearchGroup and age?
summary(lm(dSingle$Holes_LH~dSingle$Research.Group+dSingle$AgeDemeaned))
# The interaction between the parameters Research Group and age is complicated to interpretate. The caracteristic of the control group has a significant impact on the outcome of the result. This does not hold true for all of the MCI subjects. 
```

```{r, echo=TRUE}
# Link between holes and the Interaction of ResearchGroup, age and sex?
summary(lm(dSingle$Holes_LH~dSingle$Research.Group + dSingle$Sex + dSingle$AgeDemeaned))
# Even when taking into account more variables, the model is still not very accurate: R-squared value
```

```{r, echo=TRUE}
# Link between holes and the Interaction of ResearchGroup, age and sex?
summary(lm(dSingle$Holes_LH~dSingle$Research.Group * dSingle$Sex * dSingle$AgeDemeaned))
# Once again the problem seems to be the linear model, that causes the problems
```

```{r, echo=TRUE}
# Lets try to fit a quadratic model:
summary(lm(log(dSingle$Holes_LH)~dSingle$Age))
```

## Test if the other metrics are also age dependant
```{r, echo=TRUE}
# Contrast to noise ratio Left Hemisphere:
summary(lm(dSingle$Contrast_WM_GM_LH_rawavg_mgz~dSingle$Age))
```


```{r, echo=TRUE}
#White matter SNR Left Hemisphere based on the norm image:
summary(lm(dSingle$SNR_white_matter_norm~dSingle$Age))
```


```{r, echo=TRUE}
#White matter SNR Left Hemisphere based on the norm image dependant on age and sex ? 
summary(lm(dSingle$SNR_white_matter_norm~dSingle$Age * dSingle$Sex))
# The WM SNR does not depend on the sex, but on the age. There are paper proving that the White matter degenerates woth age
```

```{r, echo=TRUE}
#Number of outliers dependant on age ? 
summary(lm(dSingle$Number_of_outliers~dSingle$Age))
# This is expected. The number of segmentation outliers is not yet known to depend on age
```



























