---
title: "Simple QC statistics "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load data
d<-read.csv("/home/wolfft/qatools/adni-results/quality_checker_v2.csv")
e<-read.csv("/home/wolfft/qatools/adni-results/adni-qc-table1.csv")
d<-merge(d,e,by.x="Subject",by.y="Image.ID")

# preprocess data
d$AgeGroup<-as.factor(round(d$Age/5)*5)
d$AgeDemeaned<-d$Age-mean(d$Age)
d$Holes_LHGroup<-as.factor(round(d$Holes_LH/20)*20)
d$Holes_RHGroup<-as.factor(round(d$Holes_RH/20)*20)
```

### Descriptive Statistics

## Number of holes

```{r, echo=FALSE}
par(mfrow=c(1,2))

boxplot(d$Holes_LH~d$AgeGroup, ylab = "Number of holes", xlab = "Age-group", main = "LH Holes over Age-group")
boxplot(d$Holes_RH~d$AgeGroup, ylab = "Number of holes", xlab = "Age-group", main = "RH Holes over Age-group")

boxplot(d$Age~d$Holes_LHGroup, ylab = "Age", xlab = "Number of holes", main = " Age over LH holes-group")
boxplot(d$Age~d$Holes_RHGroup, ylab = "Age", xlab = "Number of holes", main = " Age over RH holes-group") 

boxplot(d$Holes_LH~d$Sex, ylab = "Number of holes", xlab = "Sex", main = "LH Holes over sex")
boxplot(d$Holes_RH~d$Sex, ylab = "Number of holes", xlab = "Sex", main = "RH Holes over sex")

boxplot(d$Holes_LH~d$Research.Group, ylab = "Number of holes", xlab = "Research Group", las = 2, main = "LH Holes over Research Group")
boxplot(d$Holes_RH~d$Research.Group, ylab = "Number of holes", xlab = "Research Group", las = 2, main = "RH Holes over Research Group")
```

### Number of defects

```{r, echo=FALSE}
par(mfrow=c(1,2))

boxplot(d$lh_defects~d$AgeGroup, ylab = "Number of defects", xlab = "Age-group", main = "LH defects over Age-group")
boxplot(d$rh_defects~d$AgeGroup, ylab = "Number of defects", xlab = "Age-group", main = "RH Defects over Age-group")

boxplot(d$lh_defects~d$Sex, ylab = "Number of defects", xlab = "Sex", main = " LH Defects over sex")
boxplot(d$rh_defects~d$Sex, ylab = "Number of defects", xlab = "Sex", main = " RH Defects over sex")

boxplot(d$lh_defects~d$Research.Group,  ylab = "Number of defects", xlab = "Research Group", las = 2, main = "LH Defects over Research Group")
boxplot(d$rh_defects~d$Research.Group,  ylab = "Number of defects", xlab = "Research Group", las = 2, main = "RH Defects over Research Group")
```

## Models
### Correlation 
```{r, echo=TRUE}
# Simple correlation between the left hemisphere holes and the age-Grou
cor(d$Age,d$Holes_LH)
```
### Linear Model
```{r, echo=TRUE}
# Original parameters LH Holes 
plot(d$Holes_LH~d$Age)
model<-lm(d$Holes_LH~d$Age)
abline(model,col="red")

```

```{r, echo=TRUE}
# Centered age LH Holes
plot(d$Holes_LH~d$AgeDemeaned)
d$AgeDemeaned<-d$Age-mean(d$Age)
model_mean<-lm(d$Holes_LH~d$AgeDemeaned)
abline(model_mean,col="red")

```


```{r, echo=TRUE}
# Look at the residues of the original model 
plot(model$residuals)
# The residuals of the centered model: 
plot(d$AgeDemeaned,model$residuals)
# Problems: Decreasing tendancy and not scattered equally
```
## Evaluation 
```{r, echo=TRUE}
# Significant link between LH Holes and Age?
model<-lm(d$Holes_LH~d$Age)
summary(model)

model_mean<-lm(d$Holes_LH~d$AgeDemeaned)
summary(model_mean)
# Yes significant link between LH Holes and Age p < 0.05 
```

```{r, echo=TRUE}
# Significant link between RH Holes and Age?
model<-lm(d$Holes_RH~d$Age)
summary(model)

model_mean<-lm(d$Holes_RH~d$AgeDemeaned)
summary(model_mean)
# Yes significant link between RH Holes and Age p < 0.05 but not exactely the same results than the LH holes. 
```


```{r, echo=TRUE}
# Significant link between LH Holes and Sex?
model<-lm(d$Holes_LH~d$Sex)
summary(model)
# Yes significant link between LH Holes and Sex p < 0.05 

```




