---
title: "QC Statistics: Example 1 holes "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load data
d<-read.csv("/home/wolfft/qatools/adni-results/quality_checker_v2.csv")
e<-read.csv("/home/wolfft/qatools/adni-results/adni-qc-table1.csv")
d<-merge(d,e,by.x="Subject",by.y="Image.ID")

# preprocess data
d$AgeGroup<-as.factor(round(d$Age/5)*5)
d$Holes_LHGroup<-as.factor(round(d$Holes_LH/20)*20)
```

## Descriptive Statistics

### Number of holes

```{r, echo=FALSE}
par(mfrow=c(1,2))

boxplot(d$Holes_LH~d$AgeGroup, main = "LH Holes over Age-group")
boxplot(d$Holes_RH~d$AgeGroup, main = "RH Holes over Age-group")

boxplot(d$Holes_LH~d$Sex, main = "LH Holes over sex")
boxplot(d$Holes_RH~d$Sex, main = "RH Holes over sex")

boxplot(d$Holes_LH~d$Research.Group, main = "LH Holes over Research Group")
boxplot(d$Holes_RH~d$Research.Group, main )
```

### Number of defects

```{r, echo=FALSE}
par(mfrow=c(1,2))

boxplot(d$lh_defects~d$AgeGroup)
boxplot(d$rh_defects~d$AgeGroup)

boxplot(d$lh_defects~d$Sex)
boxplot(d$rh_defects~d$Sex)

boxplot(d$lh_defects~d$Research.Group)
boxplot(d$rh_defects~d$Research.Group)
```

## Models

```{r, echo=FALSE}



```








