name: build
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [stable]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          #architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off .[build]
      - name: Test package install
        run: run_fsqc
      - name: Remove package install
        run: python -m pip uninstall -yq fsqc
      - name: Build package
        run: python -m build
      - name: Install sdist
        run: pip install ./dist/*.tar.gz
      - name: Test sdist install
        run: run_fsqc
      - name: Remove sdist install
        run: python -m pip uninstall -yq fsqc
      - name: Install wheel
        run: pip install ./dist/*.whl
      - name: Test wheel install
        run: run_fsqc
      - name: Remove wheel install
        run: python -m pip uninstall -yq fsqc
