name: code-style
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [stable]
  workflow_dispatch:

jobs:
  style:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off .[style]
      - name: Run Ruff
        run: ruff check .
      - name: Run isort
        uses: isort/isort-action@master
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "23.10.1"
      - name: Run codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          skip: './.git,./build,./.mypy_cache,./.pytest_cache'
          ignore_words_file: ./.codespellignore
